package types;

public enum TipoPico {

	GENERALISTA, INSECTIVORO, GRANIVORO, COMEDOR_SEMILLAS, NECTARIVORO, FRUGIVORO, CARPINTERO,
	PICO_BOLSA, LIMICOLA, FILTRADOR, PESCADOR, BUCEADOR, CARRONIERO, DE_PRESA;
	
}
